In [1]:
import os, sys
sys.path.insert(0, os.path.abspath(".."))

import numpy as np
from sklearn import datasets

from core.globals import reset_notebook_state

from sklearn.neighbors import KNeighborsClassifier

reset_notebook_state()

In [2]:
from core.io.filesystem_adapter import FilesystemAdapter
from core.io.recover import resume

graph = resume(FilesystemAdapter())

In [3]:
# Recompute trimmed nodes.
graph.recompute_graph(globals())

Recomputing edge cell_4...
{'indices': array([141, 139,  73, 110,  55, 130,  83,  50, 114,  44, 118,  78,  16,
       123,  53,  84,   9, 119,  64,   3,  60, 136, 140,  39,  87,  99,
       133, 100,  45, 138,  10,  25, 107,  49,  96,  57,  71,  86,  85,
        48,  66,  91,   1,  77,  89,  63,  80,  22,   0,  32,  61,  81,
        31,  24, 125,  14, 148,  35,  38,  75, 147,   8,  19, 116,  70,
       101,  76, 137, 129, 109,   2, 144, 113,   7,   5,  42,  97,  28,
        47,  54, 134, 122, 142,  41,  11,  29, 128,  52,  12, 120,  37,
       112,  20,   6,  98,  65,  26, 146,  43, 132,  56, 105,  30,  40,
       115,  21, 117, 149,  67,   4,  58,  51,  92,  62,  13, 102, 108,
        36,  82, 145,  93, 103, 131,  33,  79,  68, 111,  46, 121,  17,
        69,  88,  23,  94,  95,  90,  34,  72,  59, 124, 126, 106, 127,
        18,  15, 143, 104, 135,  74,  27]), 'iris_X_train': array([[6.9, 3.1, 5.1, 2.3],
       [6.9, 3.1, 5.4, 2.1],
       [6.1, 2.8, 4.7, 1.2],
       [6.5, 3.2, 5.1,

In [4]:
# Reconstruct the notebook by declaring variables and functions into the kernel.
graph.reconstruct_notebook()

In [5]:
from core.globals import operation_events, variable_snapshots

for x in operation_events:
    print(x, "\n")
    print("input variable_snapshots: \n")
    for y in x.input_variable_snapshots:
        print(y, "\n")
    print("------------")

Operation with name cell_2 and id 0 started at 2022-09-25 22:18:50.148924 and ended at 2022-09-25 22:18:50.150743, 0.001819 s elapsed, 0 input variable snapshots 

input variable_snapshots: 

------------
Operation with name cell_3 and id 1 started at 2022-09-25 22:18:50.156266 and ended at 2022-09-25 22:18:50.156284, 1.8e-05 s elapsed, 0 input variable snapshots 

input variable_snapshots: 

------------
Operation with name cell_4 and id 2 started at 2022-09-25 22:18:50.161679 and ended at 2022-09-25 22:18:50.161873, 0.000194 s elapsed, 2 input variable snapshots 

input variable_snapshots: 

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]


In [6]:
print("variable snapshots:")
for x in variable_snapshots:
    print(x)

variable snapshots:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4