In [1]:
import os, sys
sys.path.insert(0, os.path.abspath(".."))

from elastic.core.globals import reset_notebook_state

from sklearn.neighbors import KNeighborsClassifier

reset_notebook_state()

In [2]:
from elastic.core.io.filesystem_adapter import FilesystemAdapter
from elastic.core.io.recover import resume

graph = resume(FilesystemAdapter())

In [3]:
# Recompute trimmed nodes.
graph.recompute_graph()

Recomputing edge import_libraries...
{'np': <module 'numpy' from '/Users/libilly/elastic_notebook2/elastic-notebook/venv/lib/python3.8/site-packages/numpy/__init__.py'>, 'datasets': <module 'sklearn.datasets' from '/Users/libilly/elastic_notebook2/elastic-notebook/venv/lib/python3.8/site-packages/sklearn/datasets/__init__.py'>}
Recomputing edge cell_2...
{'iris_X': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 

In [4]:
# Reconstruct the notebook by declaring variables and functions into the kernel.
graph.reconstruct_notebook()

In [5]:
from elastic.core.globals import operation_events, variable_snapshots

for x in operation_events:
    print(x, "\n")
    print("input variable_snapshots: \n")
    for y in x.input_variable_snapshots:
        print(y, "\n")
    print("------------")

Operation with name cell_2 and id 0 started at 2022-10-14 16:33:18.856775 and ended at 2022-10-14 16:33:18.858801, 0.002026 s elapsed, 0 input variable snapshots 

input variable_snapshots: 

------------
Operation with name cell_3 and id 1 started at 2022-10-14 16:33:18.867863 and ended at 2022-10-14 16:33:18.867883, 2e-05 s elapsed, 0 input variable snapshots 

input variable_snapshots: 

------------
Operation with name cell_4 and id 2 started at 2022-10-14 16:33:18.876162 and ended at 2022-10-14 16:33:18.876231, 6.9e-05 s elapsed, 2 input variable snapshots 

input variable_snapshots: 

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2] 

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]

In [6]:
print("variable snapshots:")
for x in variable_snapshots:
    print(x)

variable snapshots:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4