In [1]:
import os, sys
sys.path.insert(0, os.path.abspath(".."))

from core.globals import reset_notebook_state

from sklearn.neighbors import KNeighborsClassifier

reset_notebook_state()

In [2]:
from core.io.filesystem_adapter import FilesystemAdapter
from core.io.recover import resume

graph = resume(FilesystemAdapter())

In [3]:
# Recompute trimmed nodes.
graph.recompute_graph()

Recomputing edge import_libraries...
{'np': <module 'numpy' from '/Users/alinayh/Desktop/elastic-notebook/.env/lib/python3.9/site-packages/numpy/__init__.py'>, 'datasets': <module 'sklearn.datasets' from '/Users/alinayh/Desktop/elastic-notebook/.env/lib/python3.9/site-packages/sklearn/datasets/__init__.py'>}
Recomputing edge cell_4...
{'indices': array([136,  75,  58, 131,  24,  86,  32, 148, 108, 125,  28,  10, 142,
       122, 143, 112, 119, 127,  62,  82,  31, 147,  13, 115, 128, 123,
        16, 111,  44,  17,  20,  42,   6,  89, 106,  48,  72, 129, 103,
        11,  23,  63, 149,  65,  87,  54,  70,  22,  26,  78,  95, 100,
        67, 118,  29,  88, 135, 117,  43,  77,  69,  52,  21,  51,  84,
        25, 139,  91,  97,  38, 144,   4,  60,  57,  68,  18, 132,  50,
        74, 133,   3,  47,  73,  53,  49, 104,  59,  76,   8,  93,   9,
       102,  40,  94,  45, 116,  37,  35,   1,   5, 105,  12,  79,  64,
       121,  99,  92,  85,  80, 137,  34, 109, 114,  41, 113, 138,  55,
   

In [4]:
# Reconstruct the notebook by declaring variables and functions into the kernel.
graph.reconstruct_notebook()

In [5]:
from core.globals import operation_events, variable_snapshots

for x in operation_events:
    print(x, "\n")
    print("input variable_snapshots: \n")
    for y in x.input_variable_snapshots:
        print(y, "\n")
    print("------------")

Operation with name cell_2 and id 0 started at 2022-10-05 17:43:38.848622 and ended at 2022-10-05 17:43:38.852499, 0.003877 s elapsed, 0 input variable snapshots 

input variable_snapshots: 

------------
Operation with name cell_3 and id 1 started at 2022-10-05 17:43:38.945829 and ended at 2022-10-05 17:43:38.945865, 3.6e-05 s elapsed, 0 input variable snapshots 

input variable_snapshots: 

------------
Operation with name cell_4 and id 2 started at 2022-10-05 17:43:39.044459 and ended at 2022-10-05 17:43:39.044571, 0.000112 s elapsed, 2 input variable snapshots 

input variable_snapshots: 

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]


In [6]:
print("variable snapshots:")
for x in variable_snapshots:
    print(x)

variable snapshots:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4