In [14]:
import os, sys
sys.path.insert(0, os.path.abspath(".."))

import numpy as np
from sklearn import datasets

import core.container
from core.record_event import RecordEvent
from core.record_event import ClearEvent

ClearEvent()

In [15]:
@RecordEvent
def cell_2():
    iris_X, iris_y = datasets.load_iris(return_X_y=True)
    
    return iris_X, iris_y

In [16]:
iris_X, iris_y = cell_2()

container created for variable  6295533200
container created for variable  6295532912


In [17]:
@RecordEvent
def cell_3():
    np.random.seed(0)

In [18]:
cell_3()

In [19]:
@RecordEvent
def cell_4():
    indices = np.random.permutation(len(iris_X))
    iris_X_train = iris_X[indices[:-10]]
    iris_y_train = iris_y[indices[:-10]]
    iris_X_test = iris_X[indices[-10:]]
    iris_y_test = iris_y[indices[-10:]]
    
    return indices, iris_X_train, iris_y_train, iris_X_test, iris_y_test

In [20]:
indices, iris_X_train, iris_y_train, iris_X_test, iris_y_test = cell_4()

container created for variable  6138860528
container created for variable  6295533968
container created for variable  6295533872
container created for variable  6295534544
container created for variable  6295534064


In [22]:
from sklearn.neighbors import KNeighborsClassifier

@RecordEvent
def cell_5():
    knn = KNeighborsClassifier()
    knn.fit(iris_X_train, iris_y_train)

    knn.predict(iris_X_test)
    
    return knn

In [23]:
knn = cell_5()

container created for variable  6297939248


In [25]:
for x in core.event.operation_events:
    print(x, "\n")
    print("related data events: \n")
    for y in x.related_data_events:
        print(y, "\n")
    print("------------")

Operation with name cell_2 and id 0 started at 2022-09-05 13:55:40.497532 and ended at 2022-09-05 13:55:40.499309, 0:00:00.001777 s elapsed, 0 related data events 

related data events: 

------------
Operation with name cell_3 and id 1 started at 2022-09-05 13:55:40.505720 and ended at 2022-09-05 13:55:40.505740, 0:00:00.000020 s elapsed, 0 related data events 

related data events: 

------------
Operation with name cell_4 and id 2 started at 2022-09-05 13:55:40.882402 and ended at 2022-09-05 13:55:40.882507, 0:00:00.000105 s elapsed, 5 related data events 

related data events: 

DataContainer with base ID 6138861104 and type <class 'numpy.ndarray'> used at 2022-09-05 13:55:40.882416, previous operation event was Operation with name cell_2 and id 0 started at 2022-09-05 13:55:40.497532 and ended at 2022-09-05 13:55:40.499309, 0:00:00.001777 s elapsed, 0 related data events 

DataContainer with base ID 6138861104 and type <class 'numpy.ndarray'> used at 2022-09-05 13:55:40.882492, pr

In [11]:
for x in core.event.data_events:
   print(x, "\n")

DataContainer with base ID 4830848560 and type <class 'numpy.ndarray'> used at 2022-09-05 13:47:06.241763, previous operation event was Operation with name cell_2 and id 0 started at 2022-09-05 13:47:05.666897 and ended at 2022-09-05 13:47:05.668917, 0:00:00.002020 s elapsed, 0 related data events 

DataContainer with base ID 4830848560 and type <class 'numpy.ndarray'> used at 2022-09-05 13:47:06.242667, previous operation event was Operation with name cell_2 and id 0 started at 2022-09-05 13:47:05.666897 and ended at 2022-09-05 13:47:05.668917, 0:00:00.002020 s elapsed, 0 related data events 

DataContainer with base ID 4830848176 and type <class 'numpy.ndarray'> used at 2022-09-05 13:47:06.242675, previous operation event was Operation with name cell_2 and id 0 started at 2022-09-05 13:47:05.666897 and ended at 2022-09-05 13:47:05.668917, 0:00:00.002020 s elapsed, 0 related data events 

DataContainer with base ID 4830848560 and type <class 'numpy.ndarray'> used at 2022-09-05 13:47:0

In [11]:
for x in core.event.data_containers:
    print(x, "\n")

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [26]:
parent_lookup = {oe: set() for oe in core.event.operation_events}
children_lookup = {oe: set() for oe in core.event.operation_events}

In [27]:
print(core.event.operation_event_lookup)

{0: <core.event.OperationEvent object at 0x1044f0b50>, 1: <core.event.OperationEvent object at 0x1044c3a90>, 2: <core.event.OperationEvent object at 0x104425580>, 3: <core.event.OperationEvent object at 0x16de5f220>, 4: <core.event.OperationEvent object at 0x1044c35b0>, 5: <core.event.OperationEvent object at 0x16de5ffa0>, 6: <core.event.OperationEvent object at 0x16e08b8b0>, 7: <core.event.OperationEvent object at 0x177620130>}


In [28]:
for oe in core.event.operation_events:
    for related_data_event in core.event.operation_event_lookup[oe.exec_uuid].related_data_events:
        parent_oe = related_data_event.prev_operation_event
        
        parent_lookup[oe].add(parent_oe)
        children_lookup[parent_oe].add(oe)

In [29]:
print(parent_lookup)
print(children_lookup)

{<core.event.OperationEvent object at 0x1044f0b50>: set(), <core.event.OperationEvent object at 0x1044c3a90>: set(), <core.event.OperationEvent object at 0x104425580>: {<core.event.OperationEvent object at 0x1044f0b50>}, <core.event.OperationEvent object at 0x16de5f220>: {<core.event.OperationEvent object at 0x104425580>}, <core.event.OperationEvent object at 0x1044c35b0>: set(), <core.event.OperationEvent object at 0x16de5ffa0>: set(), <core.event.OperationEvent object at 0x16e08b8b0>: {<core.event.OperationEvent object at 0x1044c35b0>}, <core.event.OperationEvent object at 0x177620130>: {<core.event.OperationEvent object at 0x16e08b8b0>}}
{<core.event.OperationEvent object at 0x1044f0b50>: {<core.event.OperationEvent object at 0x104425580>}, <core.event.OperationEvent object at 0x1044c3a90>: set(), <core.event.OperationEvent object at 0x104425580>: {<core.event.OperationEvent object at 0x16de5f220>}, <core.event.OperationEvent object at 0x16de5f220>: set(), <core.event.OperationEvent